# fly.toml app configuration file generated for rough-wind-2313 on 2023-08-26T01:08:06-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "rough-wind-2313"
primary_region = "bos"

[build]
dockerfile = "server/Dockerfile"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
